### ISSUE TITLE
[Portfolio, Delegation] Avatars of validators with name in multiple lines squished

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#303] opened 2022-07-21 11:02 UTC
build: dev / mainnet
device: iphone 12/ safari

## Description
When it's mobile view, the Avatar of the first validator in "your stake" will become Rounded Rectangle

## Expected results
Should be a normal circle

## Screenshot
<img src="https://zube.io/files/oursky/4ab701e5896f0def4c013bd936cda32d-img_7555.png" width="40%">

**Comment by joyzoursky** [comment] 2022-07-21 13:18
It happens when the validator's name breaks into multiple lines, not relating to the sequence. If it is in one line, it will display circle properly.

Testing validator: https://mainnet.likedao-dev.pandawork.com/portfolio/cosmos1qly96sy3yklkwv6cf4he5ves4qu8yn586gnqjk

<img width="1515" alt="Screenshot 2022-07-21 at 9 15 20 PM" src="https://user-images.githubusercontent.com/12539486/180223105-0a20aab6-842a-42c1-8232-6e47f1ad5add.png">

<img width="1515" alt="Screenshot 2022-07-21 at 9 16 24 PM" src="https://user-images.githubusercontent.com/12539486/180223077-0668487e-e0c6-4ac3-9bec-f0da369e78ce.png">

**Comment by hochiw** [comment] 2022-07-24 16:41
i think @ivanng-oursky says he fixed it in his latest pr, will double check, move to Code Review first

**Comment by hochiw** [comment] 2022-07-27 08:58
Fixed via https://github.com/oursky/likedao/pull/293/commits/a2806b2dbd34db389dc67aa75ac82f247b90ee5e

**Comment by joyzoursky** [comment] 2022-07-28 15:40
Handling changed for the table view, cannot reproduce now.

**Closed by joyzoursky** 2022-07-28 15:40 UTC
Labels: reported by qa, reported by team, ui/major, [zube]: PM Acceptance
